name: 'ftp-clean'
author: 'Taylor Gibb <taylor@developerhut.co.za>'
description: 'Github action to clean an FTP location'
inputs:
  host:
    description: 'FTP host'
    required: true
  user:
    description: 'FTP user'
    required: true
  password:
    description: 'FTP password'
    required: true
  exclude:
    description: 'Files and directories which should be excluded from being removed.'
    required: true
    default: '["source.zip"]'
runs:
  using: 'node12'
  main: 'dist/index.js'
branding:
  color: 'orange'
  icon: 'delete'